### ISSUE TITLE
How are you counting `iscrowd=1` instances ?

### ISSUE THREAD

**Issue by IssamLaradji** [prithv1/cvpr2017_counting#4]
I am trying to obtain the ground truth count you have in `coco_val_gt.mat` using the original `instances_val2014.json`.

I noticed that for images with instances with `iscrowd=1`,  you add `1`, `2`, or `3` to the count corresponding to that instance category. Is there a way I can determine the count for the `iscrowd=1` instances ?

Thanks!

**Comment by prithv1** [comment]
Sorry about the delay. The ground truth counts are obtained from the bounding box annotations. Just aggregate the number of bounding boxes per class in an image to get a ground truth count vector corresponding to all the classes.
